### PR TITLE
Wrap the FLAME installation process in a script

### PR DESCRIPTION
**Pull request by rht**
This is so that it can be reused in a Dockerfile.

### CODE REVIEW

**Comment by rht** [comment]
Installation using libmboard 0.3.1 failed: https://travis-ci.com/ETACE/eurace_unibi/builds/98492936. Then the install is fine once it uses master.

**Comment by rht** [comment]
The libmboard download version could be pegged to a hash: https://github.com/FLAME-HPC/libmboard/archive/5fd34e83b932dcda5bb6c177277b8557fbe01229.tar.gz.

**Comment by rht** [comment]
Rebased with the commit amended to pegging to a hash instead of a mutable reference (master).

**Comment by rht** [comment]
Test errors (some happen multiple times):
```
ClearingHouse_unittests.c:110:113: error: ‘m_index_info {aka struct m_index_info}’ has no member named ‘price’
 re = %f price = %f moving_avg_price=%f\n", value, index_info_message->price, in
                                                                     ^
ClearingHouse_unittests.c:110:140: error: ‘m_index_info {aka struct m_index_info}’ has no member named ‘moving_avg_price’
 vg_price=%f\n", value, index_info_message->price, index_info_message->moving_av
                                                                     ^
Household_unittests.c:54:5: error: too many arguments to function ‘add_index_info_message’
     add_index_info_message(dividend_per_share, price, moving_avg_price);
     ^

gcc: error: ../Firm_Financial_Management_Functions_update_var.c: No such file or directory
gcc: error: ../Firm_Financial_Management_Functions_ref.c: No such file or directory

gcc: error: ../Mall_aux_functions.c: No such file or directory
gcc: error: ../Firm_Producer_Functions.c: No such file or directory

Eurostat_unittests.c:25:5: error: too few arguments to function ‘add_firm_data’
     add_firm_data(&REGION_FIRM_DATA,
     ^
Eurostat_unittests.c:49:5: error: too few arguments to function ‘add_household_data’
     add_household_data(&REGION_HOUSEHOLD_DATA,
     ^
Eurostat_unittests.c:58:5: error: too few arguments to function ‘add_household_data’
     add_household_data(&REGION_HOUSEHOLD_DATA,
     ^
Eurostat_unittests.c:137:5: error: too few arguments to function ‘add_firm_send_data_message’
     add_firm_send_data_message(0,0,0,0, 0,0,0,0,0, 0,0, 0,0,0,0,0, 0,0,0,0,0,0,
     ^
Eurostat_unittests.c:401:5: error: too few arguments to function ‘add_household_data’
     add_household_data(&REGION_HOUSEHOLD_DATA,
     ^
Eurostat_unittests.c:442:5: error: too few arguments to function ‘add_household_send_data_message’
     add_household_send_data_message(0,1,1,1, 0.0, 0.0);
     ^
Eurostat_unittests.c:1765:9: error: too few arguments to function ‘add_region_data_item’
         add_region_data_item(&HISTORY_QUARTERLY[k].region_data,
         ^
Household_unittests.c:21:19: error: ‘LIST_OF_BANKRUPT_FIRMS’ undeclared (first use in this function)
  reset_int_array(&LIST_OF_BANKRUPT_FIRMS);
                   ^
gcc: error: unittest_suite_my_library.c: No such file or directory
```

**Comment by rht** [comment]
I have fixed all the gcc errors, but will push the fix once this PR is merged so that the size of this PR is not too big.

**Comment by svdhoog** [comment]
A Dockerfile is a good idea. But please do not add commits to a PR that are not related to the issue of the title, such as putting the its/* files in .gitignore, or fixing bugs in the unittests. IMHO those should be in a separate PR.

**Comment by rht** [comment]
I have already removed the its commits.

**Comment by svdhoog** [comment]
OK done.

**Comment by rht** [comment]
@svdhoog should I update the readme to libmboard Sep 18 2018 version instead of 0.3.1 as well?

**Comment by svdhoog** [comment]
Basically, we should ask the maintainers to release Libmboard 0.3.2 from the master HEAD, right?
AFAIU, you showed that 0.3.1 has a problem, right?

**Comment by svdhoog** [comment]
@rht A solution was mentioned on FLAME-HPC issue list:

https://github.com/FLAME-HPC/libmboard/issues/1

The user set `chmod u+x autogen.sh`, which is slightly different from your `chmod +x autogen.sh`.
Does this resolve the issue with libmboard 0.3.1, or should master still be used instead?

**Comment by rht** [comment]
The problem is not just `autogen.sh`. It works after the executable patch. `automake` is what went wrong https://travis-ci.com/ETACE/eurace_unibi/builds/98492936#L263.

**Pull request merged**
